Adds task to resolve packages when setup is called by itself
wooga/atlas-wdk-unity pull request #66
Opened 2022-12-15 14:47 UTC by Azurelol

## Description

Adds a task, `resolvePackages`, which has been added onto the pseudo `setup` lifecycle task this plugin adds. It will be called whenever `setup` is invoked by itself, with no other Unity tasks.

## Changes
* ![ADD] `resolvePackages` task, `setup` task dependency

[NEW]:      https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]:      https://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:  https://resources.atlas.wooga.com/icons/icon_improve.svg "Improve"
[CHANGE]:   https://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:      https://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:   https://resources.atlas.wooga.com/icons/icon_update.svg "Update"

[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:  https://resources.atlas.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:    https://resources.atlas.wooga.com/icons/icon_webGL.svg "WebGL"
[GRADLE]:   https://resources.atlas.wooga.com/icons/icon_gradle.svg "GRADLE"
[UNITY]:    https://resources.atlas.wooga.com/icons/icon_unity.svg "Unity"
[LINUX]:    https://resources.atlas.wooga.com/icons/icon_linux.svg "Linux"
[WIN]:      https://resources.atlas.wooga.com/icons/icon_windows.svg "Windows"
[MACOS]:    https://resources.atlas.wooga.com/icons/icon_iOS.svg "macOS"

2022-12-15 14:50 UTC, Larusso requested changes

2022-12-15 14:50 UTC, Larusso commented on src/main/groovy/wooga/gradle/wdk/unity/tasks/ResolvePackages.groovy
> +    static String lockFileName = "packages-lock.json"
remove these for now.

2022-12-15 14:52 UTC, Azurelol commented on src/main/groovy/wooga/gradle/wdk/unity/tasks/ResolvePackages.groovy
> +    static String lockFileName = "packages-lock.json"
yes

2022-12-16 12:55 UTC, Larusso approved these changes

2022-12-16 12:56 UTC, merged